# Generated by Django 4.2.5 on 2023-10-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaloriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6)),
                ('heartRate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bodyTemp', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
